# Generated by Django 6.0.1 on 2026-01-26 02:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rarity', models.CharField(choices=[('COMMON', 'Common'), ('RARE', 'Rare'), ('EPIC', 'Epic'), ('LEGENDARY', 'Legendary')], default='COMMON', max_length=20)),
                ('item_type', models.CharField(choices=[('WEAPON', 'Weapon'), ('ARMOR', 'Armor'), ('CONSUMABLE', 'Consumable')], max_length=20)),
                ('item_slot', models.CharField(blank=True, choices=[('HEAD', 'Head'), ('CHEST', 'Chest'), ('HAND', 'Hand')], max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('xp', models.PositiveIntegerField(default=0)),
                ('level', models.PositiveIntegerField(default=1)),
                ('hp', models.IntegerField(default=100)),
                ('max_hp', models.IntegerField(default=100)),
                ('strenght', models.IntegerField(default=10)),
                ('x_pos', models.IntegerField(default=0)),
                ('y_pos', models.IntegerField(default=0)),
                ('direction', models.IntegerField(choices=[(0, 'North'), (1, 'East'), (2, 'South'), (3, 'West')], default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItemInInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='game.hero')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.item')),
            ],
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_level', models.IntegerField()),
                ('width', models.IntegerField(default=10)),
                ('height', models.IntegerField(default=10)),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maps', to='game.hero')),
            ],
        ),
        migrations.CreateModel(
            name='Enemy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('hp', models.IntegerField()),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('map_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enemies', to='game.map')),
            ],
        ),
        migrations.CreateModel(
            name='ItemSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_name', models.CharField(choices=[('HEAD', 'Head'), ('CHEST', 'Chest'), ('MAIN_HAND', 'Main Hand'), ('OFF_HAND', 'Off Hand')], max_length=20)),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_slot', to='game.hero')),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='item_slot', to='game.itemininventory')),
            ],
            options={
                'unique_together': {('hero', 'slot_name')},
            },
        ),
        migrations.CreateModel(
            name='MapTile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('tile_type', models.CharField(choices=[('EMPTY', 'Empty Pathway'), ('WALL', 'Wall'), ('ENEMY', 'Enemy Spawn'), ('CHEST', 'Treasure Chest')], max_length=20)),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.map')),
            ],
            options={
                'unique_together': {('map', 'x', 'y')},
            },
        ),
    ]
