# Generated by Django 6.0.1 on 2026-01-28 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('rarity', models.CharField(choices=[('COMMON', 'Common'), ('RARE', 'Rare'), ('EPIC', 'Epic'), ('LEGENDARY', 'Legendary')], default='COMMON', max_length=20)),
                ('type', models.CharField(choices=[('WEAPON', 'Weapon'), ('ARMOR', 'Armor'), ('CONSUMABLE', 'Consumable')], max_length=20)),
                ('slot', models.CharField(blank=True, choices=[('HEAD', 'Head'), ('CHEST', 'Chest'), ('MAIN_HAND', 'Main Hand'), ('OFF_HAND', 'Off Hand')], max_length=20, null=True)),
                ('base_strength', models.IntegerField(default=0)),
                ('base_defense', models.IntegerField(default=0)),
                ('base_damage', models.PositiveIntegerField(default=0)),
                ('base_hp', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('xp', models.PositiveIntegerField(default=0)),
                ('level', models.PositiveIntegerField(default=1)),
                ('current_hp', models.IntegerField(default=100)),
                ('base_hp', models.IntegerField(default=100)),
                ('base_strength', models.IntegerField(default=10)),
                ('base_defense', models.IntegerField(default=10)),
                ('x_pos', models.IntegerField(default=0)),
                ('y_pos', models.IntegerField(default=0)),
                ('direction', models.IntegerField(choices=[(0, 'North'), (1, 'East'), (2, 'South'), (3, 'West')], default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GameLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='game.hero')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItemInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_equipped', models.BooleanField(default=False)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='game.hero')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.itemtemplate')),
            ],
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.IntegerField(default=10)),
                ('height', models.IntegerField(default=10)),
                ('map_level', models.IntegerField()),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maps', to='game.hero')),
            ],
        ),
        migrations.AddField(
            model_name='hero',
            name='current_map',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='heroes_on_map', to='game.map'),
        ),
        migrations.CreateModel(
            name='Enemy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('hp', models.IntegerField()),
                ('damage', models.IntegerField()),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('map_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enemies', to='game.map')),
            ],
        ),
        migrations.CreateModel(
            name='MapTile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('type', models.CharField(choices=[('EMPTY', 'Empty Pathway'), ('WALL', 'Wall'), ('EXIT', 'Level Exit'), ('CHEST', 'Treasure Chest')], default='EMPTY', max_length=20)),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiles', to='game.map')),
            ],
            options={
                'unique_together': {('map', 'x', 'y')},
            },
        ),
    ]
