# Generated by Django 6.0.1 on 2026-01-28 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='current_map',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='heroes_on_map', to='game.map'),
        ),
        migrations.AlterField(
            model_name='map',
            name='map_level',
            field=models.IntegerField(default=1),
        ),
    ]
