# Generated by Django 6.0.1 on 2026-01-22 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_item_inventoryslot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_number', models.IntegerField()),
                ('layout_data', models.JSONField(default=dict, help_text='JSON struktura granic mapy')),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maps', to='game.hero')),
            ],
        ),
        migrations.CreateModel(
            name='Enemy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('hp', models.IntegerField()),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('map_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enemies', to='game.map')),
            ],
        ),
    ]
